---

- name: install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
    # upgrade: yes

- name: copy apache pre-configured files
  copy:
    src: /home/gabyf/ansible-devops/roles/apache/files/monsite.conf
    dest: /etc/apache2/sites-available/monsite.conf
    owner: root
    group: root
    mode: 0644

- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - configure apache2
    - restart apache2

    


