- name: install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
    # upgrade: yes
 
- name: create path to expose with apache2
  file:
    path: {{ dev_web_path }}
    state: directory

- name: copy apache pre-configured files
  copy:
    src: /home/gabyf/ansible-devops/roles/apache/files/monsite.conf
    dest: {{ site_apache_vhost }}
    owner: root
    group: root
    mode: 0644

- name: install php and dependancies
  apt:
    name: {{ item }}
    state: present
    with_items:
      - php
      - php-mysql
      - libapache2-mod-php

- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - configure apache2
    - restart apache2

    


