- name: start mysql
  service:
    name: mysqld
    state: started
    enabled: true

- name: restart mysql
  service:
    name: mysqld
    state: restarted

- name: create wpdb
  mysql_db:
    name: wpdb
    state: present
