---

- name: Lancement du playbook déployant vsftpd/apache2/php
  hosts: webserver
  tasks:
    include_role:
      name: {{ item.name }}
    with_items:
      - "{{ roles-web }}"

- name: Lancement du déployant mysqld
  hosts: database
  tasks:
    include_role:
      name: {{ item.name }}
    with_items:
      - "{{ roles-db }}"
